### ISSUE TITLE
Id Use

### ISSUE THREAD

**Issue by jim-rosales** [tagghurtubise/prj-rev-bwfs-dasmoto#3]
According to the MDN docs the [id](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) element  "must be unique in the whole document." In this case, you've used the supplies id three times. 

To solve this, you have a couple of options the first is to cover the id to a class since an element can have multiple classes.

For example:
```HTML
      <h2 class="brushes supplies">Brushes</h2>
```

Then your CSS rule you'd update like so:
```CSS
.supplies {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

The other option is to forgo the supplies selector all together and apply the desired styles directly to the h2 element like so:

```HTML
      <h2 class="brushes">Brushes</h2>
```

Then your CSS:
```CSS
h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/tagghurtubise/prj-rev-bwfs-dasmoto/blob/f0e7fbcc324d61099cba373693c6cd0706b79c95/Dasmoto's%20Arts%20%26%20Crafts/index.html#L13
